version: '3.8'

services:
    backend: 
      build: ./backend
      ports:
        - 8080:8080
      container_name: backend
      environment: 
        - REDIS_HOST=redis
    redis:
      image: redis
      container_name: redis
      restart: unless-stopped
    frontend: 
      build: ./frontend
      ports:
        - 5000:5000
      container_name: frontend